# Generated by Django 3.1.1 on 2020-09-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='File',
        ),
    ]
